Feature 82 statistics pdf
Metatavu/oss-surveys-management pull request #84
Opened 2023-09-11 07:19 UTC by Jdallos

2023-09-14 17:57 UTC, lauriLukkarinen requested changes

2023-09-14 17:57 UTC, lauriLukkarinen commented on src/components/statistics/survey-statistics.tsx
> +    }
```suggestion
    const { answerDistributionCharts, popularTimesAndDeviceCharts } = combinedChartsData || {};
    const chartsHaveData = answerDistributionCharts?.length && popularTimesAndDeviceCharts?.length;
    const shouldUpdatePdfInstance = surveyStatistics && renderPdfCharts && chartsHaveData;

    if (!shouldUpdatePdfInstance) {
      return;
    }
```

2023-09-14 17:57 UTC, lauriLukkarinen commented on src/localization/fi.json
> +    "pdfGenerate": "Luoda pdf",
```suggestion
    "pdfGenerate": "Luo PDF",
```

2023-09-18 06:09 UTC, Jdallos commented on src/components/statistics/survey-statistics.tsx
> +      link.parentNode?.removeChild(link);
Done

2023-09-18 06:21 UTC, Jdallos commented on src/components/statistics/pdf-horizontal-chart.tsx
> +  data: any[];
Nope, just copied and pasted from the original horizontal chart. Have now typed pdf and original appropriately

2023-09-20 10:08 UTC, lauriLukkarinen approved these changes

2023-09-20 10:19 UTC, merged